version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=progress_tracker
      - DB_PASSWORD=admin
      - DB_PORT=5432

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=progress_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: