name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend
        run: curl -X POST "$FRONTEND_DEPLOY_URL"
        env:
          FRONTEND_DEPLOY_URL: ${{ secrets.FRONTEND_DEPLOY_URL }}

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend
        run: curl -X POST "$BACKEND_DEPLOY_URL"
        env:
          BACKEND_DEPLOY_URL: ${{ secrets.BACKEND_DEPLOY_URL }}
