name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main
    paths:
      - "gym-progress-tracker/frontend/**"
      - "gym-progress-tracker/backend/**"

jobs:
  deploy-frontend:
    if: contains(github.event.head_commit.modified, 'gym-progress-tracker/frontend/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Frontend
        run: curl -X POST "$FRONTEND_DEPLOY_URL"
        env:
          FRONTEND_DEPLOY_URL: ${{ secrets.FRONTEND_DEPLOY_URL }}

  deploy-backend:
    if: contains(github.event.head_commit.modified, 'gym-progress-tracker/backend/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Backend
        run: curl -X POST "$BACKEND_DEPLOY_URL"
        env:
          BACKEND_DEPLOY_URL: ${{ secrets.BACKEND_DEPLOY_URL }}
